language: php

before_script:
  - travis_retry composer update --prefer-dist $DEPENDENCIES

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: 7.3
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: Static Analysis
      script: vendor/bin/phpstan analyse

    - stage: Test
      script: vendor/bin/phpunit

    - stage: Mutation Tests
      script: vendor/bin/infection --min-msi=100 --min-covered-msi=100

    - stage: Code Style
      script: vendor/bin/phpcs

    - stage: Dependencies Check
      script: vendor/bin/composer-require-checker

    - stage: Backwards Compatibility Check
      script: vendor/bin/roave-backward-compatibility-check
